# Docker file for a slim Ubuntu-based Python3 image
FROM ubuntu:latest
MAINTAINER navi86 "krylov.ivan86@gmail.com"

RUN apt-get  update \
  && apt-get install -y python3-pip python3-dev \
  && apt-get clean \
  && apt-get remove -y python3-pip python3-dev \
  && rm -rf /var/lib/apt/lists/* \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip

ENTRYPOINT ["python3"]
