CREATE TABLE requirements(id INT(11) AUTO_INCREMENT PRIMARY KEY, description VARCHAR(255), rgroup VARCHAR(255));

INSERT INTO requirements(description, rgroup) VALUES ("Short time to market", "business");
INSERT INTO requirements(description, rgroup) VALUES ("Minimum deployment time", "business");
INSERT INTO requirements(description, rgroup) VALUES ("Minimum down time", "business");
INSERT INTO requirements(description, rgroup) VALUES ("Cost reduction", "business");
INSERT INTO requirements(description, rgroup) VALUES ("Reduce vendor lock in", "business");
INSERT INTO requirements(description, rgroup) VALUES ("SDDC Governance", "business");
INSERT INTO requirements(description, rgroup) VALUES ("Execution and Monitoring", "business");
INSERT INTO requirements(description, rgroup) VALUES ("Follow the business model with data and workload mobility", "business");
INSERT INTO requirements(description, rgroup) VALUES ("AWS-Like experience", "business");
INSERT INTO requirements(description, rgroup) VALUES ("It will not fail due to technology", "business");
INSERT INTO requirements(description, rgroup) VALUES ("Protect company secrets at all costs", "business");
INSERT INTO requirements(description, rgroup) VALUES ("Apple time-machine-like solution", "business");
INSERT INTO requirements(description, rgroup) VALUES ("Consistent, automated, and auditable documentation", "business");
INSERT INTO requirements(description, rgroup) VALUES ("All infrastructure is - Gold service with up to 99,9X Availability", "business");
INSERT INTO requirements(description, rgroup) VALUES ("Supportable solution - possibly end-2-end vendor support / avoid finger pointing", "business");
INSERT INTO requirements(description, rgroup) VALUES ("Industry leading vendor providing stable support over time", "business");
INSERT INTO requirements(description, rgroup) VALUES ("Maximum level of automation", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Hyper converged", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Scale out capability", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Enable open hypervisor", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Reproducible, standard, secure", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Configuration management tool", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Support agility", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Workload mobility", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Infrastructure as code (Network, FW, LB)", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("All infrastructure is GOLD there is no silver or bronze when it comes to infrastructure", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Nothing gets to production until it is fully monitored", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Ability to audit who, what, where, and when", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Instant point in time copy (Snapshot) feature needs to be available (cloning / babkup / timemachine)", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Reporting and trending capabilities especially for capacity and performance", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Different storage tiers, depending on performance requirements vs. cost (High performance, Standard Performance, Archival)", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Storage automated dynamic tiering", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Compression and dedupe is must for storage", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Storage and backup solutions have to be supported by major vendors for enterprise DB, Application and OS products (SAP, Oracle, MS SQL, NoSQL) OS Linux (Suse), Windows (2012 and 2016) RedHat", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Solution needs to be highly scalable (capacity and performance).  Adding / removing resources need to be simple and non-disruptive", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Non disruptive updates and changes on any Hardware or Software component", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Flexible and automated and non disruptive config changes (volume resizing, data migration, backup policies adjustments)", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Storage performance and resource allocation (IOPS, Connection to Storage, Bandwidth)", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Integration into existing monitoring solutions (SCOM and Omnibus)", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("2 hours - RTO for Gold Level Systems", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("2 hours - RPO for Gold Level Systems up to 24 hours - RPO for other categories", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("11 years - long-term backup retention 35 years and more - archiving", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("API Interface to CMDB / ServiceNow to trigger and detect config changes", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Data Migration capabilities between different regions / facilities", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Migration capabilities from existing environment to new Software Defined-Datacenter Environment", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("CEF storage (Cleversafe or Panzura) should be able to meet up to 80pct storage needs", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Backup at rest must be encrypted", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Capacity planning and automatic request for ordering should be triggered for Systems, Storage, and Networking", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Every system must be tested 1-2 months", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("White listed micro segmentation", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Fully redundant Data Center network with 99.9X reliability in design", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Bandwidth capacity planning for Application access via DC or Pub. Cloud", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Multitenancy environment with FW between tenants (security Zones with M-VRF today)", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Alleviate a challenge with Windows and Linux licensing for Hypervisor (VMWare today)", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Ability to snapshot VM to a higher capacity hardware, so Virtualization team is not involved", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Automatic decommission must be implemented carefully due to the failures in the past", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Infrastructure must be ready for breathing applications", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Service that automatically scans and hardens image to standard before Nessus", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Micro-Segmentation for MIND and Data Center with security checkpoints", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Next-Gen End Point (Micro-segmentation)", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Segmentation FW at Strategic Production sites", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Centralized FW management", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Automate the scanning and hardening or systems");
INSERT INTO requirements(description, rgroup) VALUES ("More control of change management servers, FWs, Network devices (Tripwire, Cylance)", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("End to End view of the storage for troubleshooting and quality services", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Be able to alocate specific resources and provide QoS", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Overcome an issue with TSM that is not able to back up VM bigger than 300 GB", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Need to have ability to restore VM in several minutes", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Throughput must scale for the next 5 years", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("L2 issues like broadcast / multicast storm must be controllable", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("L2 bridging must be avoided by design", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Support for dynamic routing protocols OSPF, OSPFv3, BGP", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Support for DHCP relay (RFC2131) subnet selector option (RFC3011)", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Full Support for IPv6 (incl. ND, MPBGP, SLAAC)", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Dual-Stack support (IPv4 and IPv6 at the same time)", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Firewall and routing functionality must fully support IPv6", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Firewall and routing functionality at line speed (10Gbps +)", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Buffer latency less or equal then 10µs", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Support for IGMPv3 and MLDv2 for L3 and L2 (snooping)", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Support for PIM in Dense and Sparse mode", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Unlimited size of Routing table entries", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Unlimited size of neighbor tables (ARP, ND cache)", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Unlimited size of MAC address or binding tables (e.g. VM bindings)", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Redundant links must be used simultaniously, non-blocking", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Support for LACP", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Support for Jumbo Frames", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Support for QoS mechanisms: CoS / DSCP remarking, shaping, LLQ, CBWFQ and CBWRED", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("All devices should been connected to the SIEM Solution prior to its golive", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Network Access Control (NAC) should be considered to prevent unauthorized systems connect to the DC Network", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Host based IDS / IPS should be included (eventually on Hypervisor Level…)", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Key Management Systems / Storages (HSMs etc) should be included for managing the keys for all encrypted Data", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Jump Host Infrastructure and System Management Components", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Authentication of administrators (privilege account management) 2 Factor Authentication", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Release process for blueprints / templates must be incorporate orchestration / automation / monitoring", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("Development of new technologies requires a review of impact on release / change / configuration (at least)", "technical");
INSERT INTO requirements(description, rgroup) VALUES ("GxP complaint - Needs to fulfill and qualify in Vendor Assessment as well as Infrastructure Qualification Process", "governance");
INSERT INTO requirements(description, rgroup) VALUES ("Disaster Recovery - Data has to be stored and needs to be accessible in at least 2 x Locations which are 10 km apart", "governance");
INSERT INTO requirements(description, rgroup) VALUES ("Periodic functional test for application recovery and workload mobility", "governance");
INSERT INTO requirements(description, rgroup) VALUES ("Storage and backup encryption for data classification Secure", "governance");
INSERT INTO requirements(description, rgroup) VALUES ("Nothing gets to production until it is fully monitored. If it is not monitored, it does not exist", "governance");
INSERT INTO requirements(description, rgroup) VALUES ("Itemized show back cost based on the service chosen", "governance");
INSERT INTO requirements(description, rgroup) VALUES ("Visibility of the deployment process - Who is working on it and what is ETA", "governance");
INSERT INTO requirements(description, rgroup) VALUES ("All blueprints must be approved by security, and if they wont fit criteria, security should treat it as one-off", "governance");
INSERT INTO requirements(description, rgroup) VALUES ("Automated PenTesting on a monthly basis", "governance");
INSERT INTO requirements(description, rgroup) VALUES ("API Interface to CMDB / ServiceNow to trigger and detect config changes", "governance");
INSERT INTO requirements(description, rgroup) VALUES ("Data Migration capabilities between different regions / facilities", "governance");
INSERT INTO requirements(description, rgroup) VALUES ("Solution must be integrated with CMDB", "governance");
INSERT INTO requirements(description, rgroup) VALUES ("Application dependency mapping should be automatic", "governance");
INSERT INTO requirements(description, rgroup) VALUES ("Better monitoring and capacity planning with clear escalation process", "governance");
INSERT INTO requirements(description, rgroup) VALUES ("Solution must be certified for Net New Qualified systems. This will resolve issues with vast majority of requests", "governance");
INSERT INTO requirements(description, rgroup) VALUES ("Service Now must become a true CMDB", "governance");
INSERT INTO requirements(description, rgroup) VALUES ("80pct of Monitoring should be standard and 20pct custom", "governance");
INSERT INTO requirements(description, rgroup) VALUES ("Changes to all parts of the solution must be automatically trailed for audit purposes", "governance");
INSERT INTO requirements(description, rgroup) VALUES ("Change version control - Changes must be able to be rolled back quickly", "governance");
INSERT INTO requirements(description, rgroup) VALUES ("API Changes must be fully documented and changes must not become effective before validation workflow approval", "governance");
INSERT INTO requirements(description, rgroup) VALUES ("Selfservice Portal for customer monitoring adjustment", "governance");
INSERT INTO requirements(description, rgroup) VALUES ("alignment of change mangement  and event mangement process ( Maintenance Windows )", "governance");
INSERT INTO requirements(description, rgroup) VALUES ("Dashborads for monitoring / service status presentation", "governance");
INSERT INTO requirements(description, rgroup) VALUES ("Monitoring needs to be involved  in the design phase of new templates and services ", "governance");
INSERT INTO requirements(description, rgroup) VALUES ("log file ( system, application, audit, automation, etc.) management and analytic", "governance");
INSERT INTO requirements(description, rgroup) VALUES ("Automated creation and maintenance of qualification documentation (e.g. logbooks) for qualified / Gxp systems", "governance");
